version: '2'
services:
  fpm:
    build: PHP7fpm
    # restart: always
    volumes:
      - ../php-backend:/var/www/html

    ports:
      - "9000:9000"

    links:
      - mysql

    networks:
      - my-container-network

  nginx:
    image: nginx:1.18
    # restart: always
    volumes:
      #- ./Nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./Nginx/fastcgi-php.conf:/etc/nginx/snippets/fastcgi-php.conf
      - ./Nginx/fastcgi.conf:/etc/nginx/fastcgi.conf
      - ./Nginx/app.vhost:/etc/nginx/conf.d/app.conf
      - ./Logs/Nginx:/var/log/nginx
      - ../php-backend:/var/www/html
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    links:
      - fpm
    networks:
      - my-container-network

  # nginx:
  #   build: Nginx
  #   # restart: always
  #   volumes:
  #     - ./Nginx/nginx.conf:/etc/nginx/nginx.conf
  #     - ./Nginx/app.vhost:/etc/nginx/conf.d/app.vhost
  #     - ./Logs/Nginx:/var/log/nginx
  #     - ../php-backend:/var/www/html
  #   ports:
  #     - "80:80"
  #     - "81:81"
  #     - "443:443"
  #   links:
  #     - fpm
  #   networks:
  #     - my-container-network

  mysql:
    container_name: mysql_container
    image: mysql:5.7
    #restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=cb_blog
    volumes:
      - ./data/db:/var/lib/mysql
      - ../database/generate-script.sql:/generate-script.sql
      - ./Mysql/create-database.sh:/create-database.sh
    networks:
      - my-container-network

  vuefront:
    build: VueApp
    volumes:
      - ../new-vue-js-frontend-2:/app
    working_dir: /app
    command: ['yarn', 'serve']
    ports:
      - "8080"
    networks:
      - my-container-network

networks:
  my-container-network:
    driver: bridge